sonar.projectKey=unicoin-validacion-apuntes
sonar.projectName=UniCoin Validacion Apuntes
sonar.sources=src,app.py
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.python.version=3.10,3.11,3.12,3.13,3.14
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.db,**/__pycache__/**,**/.pytest_cache/**,uploads/**
sonar.qualitygate.wait=false
